version: '3.8'

services:
  dash:
    # The image I upload to my docker hub
    image: tpattra/pattranit_web
    # For MAC M1 user
    platform: linux/x86_64
    # This will ask DASH to run on 0.0.0.0 and port 80
    environment:
      - HOST=0.0.0.0
      - PORT=80
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web_service-st123050.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is <service_name>-<folder_name>
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web_service-st123050.rule=Host(`st123050.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web_service-st123050.tls=true
      - traefik.http.routers.web_service-st123050.tls.certresolver=production
      - traefik.http.routers.web_service-st123050.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true