name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r Homework/A3-Car-Prices_classification/requirement.txt
    - name: Run tests
      run: python Homework/HW3_App_Predicting_Car_Price_Classification/test/testing.py